version: '3.1'

services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toy_market
      MYSQL_USER: dkozhenenko
      MYSQL_PASSWORD: Qw12345678